# Claude Code 統合用 GitHub Action
#
# このワークフローにより、Claude Code が GitHub の Issue や
# プルリクエストを自動的に処理し、どこからでも PKM を管理できます。
#
# セットアップ手順:
# 1. このファイルを vault リポジトリの .github/workflows/claude.yml にコピー
# 2. Claude Code OAuth トークンを取得: https://code.claude.com/docs/en/github-actions
# 3. リポジトリにトークンをシークレットとして追加:
#    - Settings > Secrets and variables > Actions に移動
#    - "New repository secret" をクリック
#    - Name: CLAUDE_CODE_OAUTH_TOKEN
#    - Value: [ステップ 2 で取得したトークン]
# 4. 必要に応じて以下のワークフロートリガーを設定

name: Claude Code PKM アシスタント

# このワークフローが実行されるタイミング
on:
  # Issue が開かれたり編集されたときにトリガー
  issues:
    types: [opened, edited]

  # Issue のコメントが作成されたときにトリガー
  issue_comment:
    types: [created]

  # プルリクエストが開かれたり編集されたときにトリガー
  pull_request:
    types: [opened, edited]

  # GitHub Actions タブから手動実行を許可
  workflow_dispatch:
    inputs:
      command:
        description: '実行する Claude コマンド'
        required: false
        default: '/daily'
        type: choice
        options:
          - '/daily'
          - '/weekly'
          - '/onboard'
          - '/push'

  # オプション: スケジュール実行（有効にするにはコメントを解除）
  # schedule:
  #   # 毎日 午前 6 時（日本時間）に実行
  #   - cron: '0 21 * * *'
  #   # 毎週日曜日 午後 8 時（日本時間）に週次レビュー実行
  #   - cron: '0 11 * * 0'

# 環境変数
env:
  # 使用する Claude Code のバージョン
  CLAUDE_CODE_VERSION: 'latest'

  # Claude で使用するデフォルトモデル
  # オプション: claude-3-opus, claude-3-sonnet, claude-3-haiku
  CLAUDE_MODEL: 'claude-3-sonnet'

  # 日付/時刻操作用のタイムゾーン
  TZ: 'Asia/Tokyo'

jobs:
  # ジョブ: GitHub Issue をタスクとして処理
  process-issue:
    name: Claude で Issue を処理
    runs-on: ubuntu-latest

    # 特定のラベルが付いた Issue でのみ実行
    if: |
      github.event_name == 'issues' &&
      (contains(github.event.issue.labels.*.name, 'task') ||
       contains(github.event.issue.labels.*.name, 'idea') ||
       contains(github.event.issue.labels.*.name, 'claude'))

    steps:
      # リポジトリをチェックアウト
      - name: リポジトリをチェックアウト
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Claude Code をセットアップ
      - name: Claude Code をセットアップ
        uses: anthropics/claude-code-action@7145c3e0510bcdbdd29f67cc4a8c1958f1acfa2f # v1.0.27
        with:
          oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          version: ${{ env.CLAUDE_CODE_VERSION }}

      # Issue を処理
      - name: Issue の内容を処理
        run: |
          # Issue の詳細を抽出
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"

          # ラベルに基づいてアクションを決定
          if [[ "${{ contains(github.event.issue.labels.*.name, 'task') }}" == "true" ]]; then
            # 今日のデイリーノートにタスクを追加
            claude code "このタスクを今日のデイリーノートに追加: $ISSUE_TITLE - $ISSUE_BODY"
          elif [[ "${{ contains(github.event.issue.labels.*.name, 'idea') }}" == "true" ]]; then
            # 適切な場所にアイデアを記録
            claude code "このアイデアを適切なプロジェクトまたはノートに記録: $ISSUE_TITLE - $ISSUE_BODY"
          fi

          # 処理完了を Issue にコメント
          gh issue comment $ISSUE_NUMBER --body "✅ Claude Code で処理され、vault に追加されました"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 変更をコミットしてプッシュ
      - name: 変更をコミット
        run: |
          git config --local user.email "claude-bot@example.com"
          git config --local user.name "Claude アシスタント"
          git add .
          git diff --staged --quiet || git commit -m "Issue #${{ github.event.issue.number }} を処理: ${{ github.event.issue.title }}"
          git push

  # ジョブ: デイリーノート作成
  daily-note:
    name: デイリーノートを作成
    runs-on: ubuntu-latest

    # スケジュール実行または手動トリガーで実行
    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.command == '/daily'

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Claude Code をセットアップ
        uses: anthropics/claude-code-action@7145c3e0510bcdbdd29f67cc4a8c1958f1acfa2f # v1.0.27
        with:
          oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

      - name: デイリーノートを作成
        run: |
          # コンテキストを読み込み
          claude code /onboard

          # 今日のデイリーノートを作成
          claude code /daily

          # オプション: 天気予報やカレンダーイベントなどを追加
          # claude code "今日の天気予報をデイリーノートに追加"
          # claude code "今日のカレンダーイベントを追加"

      - name: デイリーノートをコミット
        run: |
          git config --local user.email "claude-bot@example.com"
          git config --local user.name "Claude アシスタント"
          git add .
          DATE=$(date +%Y-%m-%d)
          git diff --staged --quiet || git commit -m "${DATE} のデイリーノート"
          git push

  # ジョブ: 週次レビュー
  weekly-review:
    name: 週次レビューを実行
    runs-on: ubuntu-latest

    # 日曜日または手動トリガーで実行
    if: |
      (github.event_name == 'schedule' && contains(github.event.schedule, '0 11 * * 0')) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.command == '/weekly')

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Claude Code をセットアップ
        uses: anthropics/claude-code-action@7145c3e0510bcdbdd29f67cc4a8c1958f1acfa2f # v1.0.27
        with:
          oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

      - name: 週次レビューを実行
        run: |
          # 全コンテキストを読み込み
          claude code /onboard all

          # 週次レビューを実行
          claude code /weekly

          # サマリーを生成
          claude code "今週の成果と来週の優先事項のサマリーを作成"

      - name: 週次レビューをコミット
        run: |
          git config --local user.email "claude-bot@example.com"
          git config --local user.name "Claude アシスタント"
          git add .
          WEEK=$(date +%Y-W%V)
          git diff --staged --quiet || git commit -m "${WEEK} の週次レビュー"
          git push

  # ジョブ: プルリクエストのスマートアシスタンス
  assist-pr:
    name: プルリクエストをアシスト
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:
      - name: PR ブランチをチェックアウト
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Claude Code をセットアップ
        uses: anthropics/claude-code-action@7145c3e0510bcdbdd29f67cc4a8c1958f1acfa2f # v1.0.27
        with:
          oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

      - name: 変更をレビュー
        run: |
          # 変更されたファイルを取得
          CHANGED_FILES=$(git diff --name-only origin/main..HEAD)

          # Claude に変更をレビューしてもらう
          claude code "これらの変更されたファイルをレビューしてフィードバックを提供: $CHANGED_FILES"

          # レビューを PR コメントとして投稿
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "$(claude code 'レビュー結果をサマリーして')"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# ワークフロー設定のノート:
#
# カスタマイズオプション:
#
# 1. **トリガー**: 'on' セクションを調整してワークフローの実行タイミングを制御
#    - 不要なトリガーを削除
#    - 自動化のためのスケジュールトリガーを追加
#    - 処理をトリガーする Issue ラベルをカスタマイズ
#
# 2. **Claude モデル**: env セクションの CLAUDE_MODEL を変更
#    - claude-3-opus: 最も高機能、複雑なタスクに最適
#    - claude-3-sonnet: バランスの取れたパフォーマンス
#    - claude-3-haiku: 最速、シンプルなタスクに適している
#
# 3. **タイムゾーン**: env セクションの TZ をローカルタイムゾーンに更新
#
# 4. **カスタムコマンド**: 特定のワークフロー用に新しいジョブを追加
#
# セキュリティノート:
#
# - CLAUDE_CODE_OAUTH_TOKEN は秘密にして、決してコミットしない
# - 可能な限り GitHub の組み込み GITHUB_TOKEN を使用
# - ワークフローを有効にする前に権限を確認
# - 機密性の高い操作には環境保護ルールの使用を検討
#
# 使用例:
#
# 1. **モバイルからタスクを作成**:
#    - GitHub モバイルアプリを開く
#    - 'task' ラベル付きの新しい Issue を作成
#    - Claude がデイリーノートに追加
#
# 2. **外出先でアイデアをキャプチャ**:
#    - 'idea' ラベル付きの Issue を作成
#    - Claude が適切なプロジェクトに記録
#
# 3. **リモートデイリープランニング**:
#    - ワークフローを手動トリガー
#    - '/daily' コマンドを選択
#    - Claude がデイリーノートを作成
#
# トラブルシューティング:
#
# - ワークフローの実行とログについては Actions タブを確認
# - CLAUDE_CODE_OAUTH_TOKEN が正しく設定されていることを確認
# - リポジトリで Actions が有効になっていることを確認
# - ファイルの権限とパスを確認
#
# 詳細情報:
# https://code.claude.com/docs/en/github-actions
